# -*- coding: utf-8 -*-
"""ML Lab 0 and 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gxco7UC3qx7XSYkkcTahuCL9AY3xL6Yr
"""

import pandas as pd
df = pd.read_csv("housing.csv")
df.head()

df.info()

df.describe()

df['ocean_proximity'].value_counts()

df.isnull().sum()[df.isnull().sum() > 0]

import pandas as pd
adult = pd.read_csv("adult.csv")
adult.head()

import numpy as np
adult.replace('?', np.nan, inplace=True)
adult.isna().sum()

import pandas as pd
# Load datasets
diabetes_df = pd.read_csv("Dataset of Diabetes .csv")
adult_df = pd.read_csv("adult.csv")

# Check missing values
print("Diabetes missing values:\n", diabetes_df.isnull().sum())
print("\nAdult missing values:\n", adult_df.isnull().sum())

categorical_cols_adult = adult_df.select_dtypes(include='object').columns
print("Categorical columns:", categorical_cols_adult)

import numpy as np
import pandas as pd

# Data Cleaning
def clean_data(df):
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].fillna(df[col].mode()[0])
        else:
            df[col] = df[col].fillna(df[col].mean())

    categorical_cols = df.select_dtypes(include='object').columns
    df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    for col in numeric_cols:
        lower = df[col].quantile(0.01)
        upper = df[col].quantile(0.99)
        df[col] = np.clip(df[col], lower, upper)

    return df

diabetes_df_clean = clean_data(diabetes_df)
adult_df_clean = clean_data(adult_df)

#Data Transformation
from sklearn.preprocessing import MinMaxScaler, StandardScaler

def transform_data(df):
    # Min-Max Scaling
    minmax_scaler = MinMaxScaler()
    df_minmax = pd.DataFrame(minmax_scaler.fit_transform(df), columns=df.columns)

    # Standard Scaling
    standard_scaler = StandardScaler()
    df_standard = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

    return df_minmax, df_standard

# Apply transformations
diabetes_minmax, diabetes_standard = transform_data(diabetes_df_clean)
adult_minmax, adult_standard = transform_data(adult_df_clean)

#Check results
print("Diabetes dataset (MinMax):")
print(diabetes_minmax.head())

print("\nAdult Income dataset (StandardScaler):")
print(adult_standard.head())